### ISSUE TITLE
The username field is not longer supported by bitbucket cloud.

### ISSUE THREAD

**Issue by landwehrj** [ip1981/bbprb#14]
Starting tomorrow, the username field will be completely removed from the author field for the pr json coming from bitbucket cloud. I think you can likely replace it with display_name to fix the issue. Currently the code is breaking for some user prs when it queries the username field from json because it is missing.

**Comment by ip1981** [comment]
https://github.com/ip1981/bbprb/commit/942c650dd2103cc7f50d5b15274c79017f60cc70
