### ISSUE TITLE
trigger on comments

### ISSUE THREAD

**Issue by lifeofguenter** [ip1981/bbprb#6]
it would be great if it could support the PR-comment trigger as well, that way a manual trigger can be done when posting a comment "please build" (configurable) in the PR.

**Comment by ip1981** [comment]
It is unlikely that I am gonna do this.

This is why:

1. It spoils discussion of PRs.
2. When a PR is created or updated it will be built anyway.
3. If someone need to rebuild a PR (e. g. for changed environment), there is the "Rebuild" button in Jenkins.
4. If this (the comment feature) is for security reasons (prevent strangers from invasion or DoS attacks), it should be much more complicated (like building PRs and accepting comments from the specific users, etc.). And I doubt that public projects with contributors you can't trust should have any automation like PR building.

I mean if triggering builds by comments seems needed, than something else is seriously broken.

**Comment by lifeofguenter** [comment]
1. Comments can be deleted - and can even be part of the plugin (=automated)

2. That is correct, this is only for the case that a build fails due to external nature, or if the jenkins job is updated

3. Actually not per default, but seeing the plugin - so thanks will give it a shot!

4. A public running jenkins has quite some issues. Someone can also just ddos by committing. A user whitelist can be made a config option (for public repos)


Aside from using a rebuild button that is the only way of easily rebuilding. So if rebuilding is not possible, that is a essential feature and surely does not show “something seriously broken”...

**Comment by ip1981** [comment]
Anyway, the question is open, I just haven't made up my mind yet.

**Comment by ip1981** [comment]
Related https://github.com/ip1981/bbprb/issues/12

**Comment by ip1981** [comment]
https://github.com/ip1981/bbprb/commit/cdef13254a2bd5c104ddbb392545828879865c16
