### ISSUE TITLE
Error 403 No valid crumb was included in the request

### ISSUE THREAD

**Issue by lifeofguenter** [ip1981/bbprb#7]
trying to implement the plugin I am receiving the following error from bitbucket:

<img width="848" alt="screen shot 2018-01-18 at 17 23 55" src="https://user-images.githubusercontent.com/241073/35105558-9e94c02a-fc74-11e7-94b2-38cadc95c150.png">

this sounds like csrf issue? But I did compare with https://github.com/jenkinsci/bitbucket-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/BitbucketHookReceiver.java#L20 so not sure what is going wrong?

**Comment by ip1981** [comment]
Indeed looks like CSFR. I don't have it enable, although for the hook it hardly makes any sense, because the hook is not protected at all. Github can use secret tokens, but Bitbucket, as fas as I know, can't.

**Comment by lifeofguenter** [comment]
There must be a way to maybe disable csrf for this plugin? Thats at least whats happening with the bitbucket and github plugin

**Comment by ip1981** [comment]
Ref. https://issues.jenkins-ci.org/browse/JENKINS-35469, https://github.com/janinko/ghprb/issues/84

**Comment by lifeofguenter** [comment]
The following plugins implemented webhooks behind CSRF:

* https://wiki.jenkins.io/display/JENKINS/BitBucket+Plugin (see: https://issues.jenkins-ci.org/browse/JENKINS-26234)
* https://plugins.jenkins.io/github (see: https://github.com/jenkinsci/github-plugin/commit/5c2a04169171cb8e36da7ba39c4003aa318c74cb)

Optionally maybe an IP based whitelist: https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html#Managewebhooks-trigger_webhookTriggeringwebhooks - that way it can not be triggered externally?

**Comment by ip1981** [comment]
Thanks, I will take a look.

As for IP whitelist, etc., the plugin is not the the right place for that. I'd use a proxy. Same for people who think they need polling instead of hooks (when Jenkins is in internal network).

In fact we use proxy (https://github.com/ip1981/sproxy2) that protects Jenkins entirely, all hooks are received on another port with strict interrogation by nginx :)

**Comment by ip1981** [comment]
Check out https://github.com/ip1981/bbprb/commit/7149adb8be3ed1c8774bf9100848fc8589e3fd18

**Comment by lifeofguenter** [comment]
<img width="846" alt="screen shot 2018-01-29 at 07 12 36" src="https://user-images.githubusercontent.com/241073/35495038-694d6916-04c7-11e8-9775-a8d2ac97390f.png">

Looks very good! Jenkins seems to be receiving the webhook, but nothing is yet happening - I strongly believe that is due to a misconfiguration on my side though :)

**Comment by jrichardsz** [comment]
In my case, this code helps me : 

https://github.com/ip1981/bbprb/commit/7149adb8be3ed1c8774bf9100848fc8589e3fd18

Thanks @ip1981
